name: GitHub Actions Demo
on: [push]

jobs:
  analyze:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - name: install dependencies
        run: flutter pub get
      - run: flutter analyze --fatal-infos --fatal-warnings .